### ISSUE TITLE
ESLint support for ST2?

### ISSUE THREAD

**Issue by brookr** [codefellows/sea-301d1#1]
Sublime Text 3 is still in Beta. Is there a good way to use ESLint from within ST2? Initial google searches turned up nothing for me.

**Comment by ivanoats** [comment]
Sublime is a dead project. I think we should focus on Atom from 101. There are installers for Windows and Linux now for atom.

**Comment by ivanoats** [comment]
Also as a work around eslint works from the command line and ST2 can shell out to it

**Comment by brookr** [comment]
Looks like it might be possible to set it up as a build system.f
